[package]
name = "matrix-gui"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Merisy-Thing <merisy-thing@outlook.com>"]
description = "embedded-graphics based GUI framework, use region-based freeform layout."
readme = "README.md"
repository = "https://github.com/Merisy-Thing/matrix-gui"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "^0.8"
multi-mono-font = { version = "0.4" }
enum-iterator = "2.3"
log = { version = "0.4", optional = true }
paste = "1.0"
embedded-text = "0.7"
saturating_cast = "0.1.0"

[dev-dependencies]
embedded-graphics-simulator = "0.8"
tinybmp = "0.7"
simple_logger = "5.2"
local_static = "0.1"

[features]
default = []

all = ["part", "fill-rect", "popup"]
anim = ["animation", "part"]

part = [
	"log",
	"focus",
	"debug-color",
	"interaction",
	"framebuffer",
]

debug-color = []
framebuffer = []
fill-rect = []
interaction = []
focus = ["interaction"]
animation = []
popup = []

[[example]]
name = "basic-example"

[[example]]
name = "fill-rect-fb"
required-features = ["fill-rect", "framebuffer"]

[[example]]
name = "anim-by-ui"
required-features = ["animation"]

[[example]]
name = "anim-demo"
required-features = ["animation"]

[[example]]
name = "msg-box"
required-features = ["popup"]