name: Feature Branch CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'
      
jobs:
  build-and-test:
    if: "!contains(github.event.pull_request.base.ref, 'main')"
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install SDL2
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Build
        run: cargo build --verbose
